/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Audio {
  id: Generated<Int8>;
  path: string;
  search: string | null;
  title: string | null;
}

export interface AudioCollection {
  id: Generated<number>;
  path: string | null;
}

export interface AudioCollectionItem {
  audio__id: Int8;
  collection__id: number;
  id: Generated<Int8>;
  slug: string;
}

export interface AudioFile {
  base__id: Int8 | null;
  format: string | null;
  id: Generated<Int8>;
  length: number | null;
  url: string | null;
}

export interface AudioTag {
  content__id: Int8;
  id: Generated<Int8>;
  tag__id: Int8;
}

export interface Base {
  citation_code_seed: Generated<number>;
  id: Generated<Int8>;
  language_code_seed: Generated<number>;
  script_code_seed: Generated<number>;
  text_code_seed: Generated<number>;
}

export interface Citation {
  accessed_at: Timestamp | null;
  category: string | null;
  format: string | null;
  id: Generated<Int8>;
  image__id: Int8 | null;
  key: string | null;
  subtitle: string | null;
  title: string;
  url: string | null;
  year: number | null;
}

export interface CitationAssociation {
  citation__id: Int8 | null;
  id: Generated<Int8>;
  object__id: string;
  object__type: string;
}

export interface CitationAuthor {
  id: Generated<Int8>;
  name: string;
  slug: string | null;
}

export interface CitationAuthorAssociation {
  author__id: Int8 | null;
  citation__id: Int8 | null;
  id: Generated<Int8>;
}

export interface ContentLicense {
  abbreviation: string | null;
  id: Generated<number>;
  is_deprecated: boolean | null;
  is_fsf_libre: boolean | null;
  is_osi_approved: boolean | null;
  jurisdiction: string | null;
  slug: string | null;
  title: string;
  url: string | null;
}

export interface ContentUsage {
  content__id: Int8;
  content__type: string;
  created_at: Timestamp;
  id: Int8;
  usage__id: Int8;
  usage__type: string;
}

export interface CorpusStringAppearanceSummary {
  corpus__id: number;
  count: Generated<number>;
  id: Generated<Int8>;
  position: Generated<number>;
  string__id: Int8;
}

export interface Country {
  abbreviation: string;
  coordinates__latitude: Numeric;
  coordinates__longitude: Numeric;
  id: Generated<number>;
  slug: string;
  title: string;
}

export interface Document {
  citation__id: Int8 | null;
  format: string;
  id: Generated<Int8>;
  path: string;
  size: number | null;
  title: string | null;
  url: string;
}

export interface DocumentCollection {
  id: Generated<number>;
  path: string;
}

export interface DocumentCollectionItem {
  collection__id: number;
  id: Generated<Int8>;
  slug: string;
  string__id: number;
}

export interface DocumentTag {
  content__id: Int8;
  id: Generated<Int8>;
  tag__id: Int8;
}

export interface FileExtension {
  value: string;
}

export interface FileNode {
  id: Generated<Int8>;
  parent__id: Int8 | null;
  record__id: Int8 | null;
  record__type: string | null;
  slug: string | null;
}

export interface FileReference {
  file__id: string;
  file__type: string;
  path: string;
}

export interface Font {
  family: string;
  id: Generated<number>;
  provider: string | null;
  slug: string;
  test: string | null;
}

export interface FontPairing {
  base__id: number | null;
  heading__id: number | null;
  id: Generated<Int8>;
}

export interface FontTag {
  content__id: Int8;
  id: Generated<Int8>;
  tag__id: Int8;
}

export interface FontVariant {
  base__id: number | null;
  id: Generated<number>;
  italic: boolean | null;
  weight: number | null;
}

export interface FontVariantChunk {
  character_set: string | null;
  format: string;
  id: Generated<number>;
  url: string;
  variant__id: number | null;
}

export interface Image {
  id: Generated<Int8>;
  path: string;
  preview: string | null;
  search: string | null;
  title: string | null;
}

export interface ImageCollection {
  id: Generated<number>;
  path: string | null;
}

export interface ImageCollectionItem {
  collection__id: number;
  id: Generated<Int8>;
  image__id: Int8;
  slug: string;
}

export interface ImageFile {
  base__id: Int8 | null;
  format: string;
  height: number;
  id: Generated<Int8>;
  size: string | null;
  url: string;
  width: number;
}

export interface ImageTag {
  content__id: Int8;
  id: Generated<Int8>;
  tag__id: Int8;
}

export interface Integer {
  divisors__count: number | null;
  divisors__set: Json | null;
  id: Generated<number>;
  value: string;
}

export interface IntegerSequence {
  description: string | null;
  id: Generated<number>;
  slug: string;
  title: string;
}

export interface IntegerSequenceAssociation {
  id: Generated<number>;
  integer__id: number | null;
  position: number;
  sequence__id: number | null;
}

export interface IntegerStringSystem {
  id: Generated<number>;
  language__id: number;
  script__id: number;
  slug: string;
}

export interface IntegerTranscriptionBinding {
  calculation: string | null;
  id: Generated<number>;
  integer__id: number;
  system__id: number;
  transcription__id: Int8;
}

export interface Job {
  completed_at: Timestamp | null;
  created_at: Timestamp;
  id: Generated<Int8>;
  output: Json;
  status: Generated<string>;
}

export interface Label {
  id: Generated<Int8>;
  slug: string;
  title: string;
}

export interface Language {
  category: string | null;
  entry_count: Generated<number>;
  family__id: number | null;
  glottolog_code: string | null;
  id: Generated<number>;
  is_constructed: boolean | null;
  is_natural: boolean | null;
  iso639_1: string | null;
  iso639_2: string | null;
  iso639_3: string | null;
  level: string | null;
  name: string;
  parent__id: number | null;
  script__id: number | null;
  slug: string;
  tags: string[] | null;
  updated_at: Timestamp | null;
}

export interface LanguageAccent {
  id: Generated<number>;
  language__id: number | null;
  name: string;
  slug: string;
}

export interface LanguageAnagram {
  component__id: Int8;
  id: Generated<Int8>;
  transcription__id: Int8;
}

export interface LanguageAnagramPermutation {
  id: Generated<Int8>;
  language__id: number;
  script__id: number;
  text: string;
}

export interface LanguageAnagramPermutationAssociation {
  child__id: Int8;
  id: Generated<Int8>;
  parent__id: Int8;
}

export interface LanguageAntonym {
  id: Generated<Int8>;
  score: Generated<Numeric>;
  source__id: Int8;
  target__id: Int8;
}

export interface LanguageCollaborator {
  added_at: Timestamp;
  id: Generated<Int8>;
  is_public: Generated<boolean | null>;
  language__id: Int8;
  role: string;
  user__id: number;
}

export interface LanguageCountry {
  country__id: number | null;
  id: Generated<number>;
  language__id: number | null;
}

export interface LanguageDefinition {
  citation__id: Int8 | null;
  id: Generated<Int8>;
  position: Generated<number>;
  provider: string | null;
  string__id: Int8 | null;
  system: string | null;
  tags: string[] | null;
  text: string | null;
  updated_at: Timestamp | null;
}

export interface LanguageDefinitionEmbedding {
  data: string;
  id: Generated<Int8>;
  language__id: number | null;
  string__id: Int8 | null;
}

export interface LanguageEncodingScheme {
  id: Generated<number>;
  name: string;
  slug: string;
  source__language__id: number | null;
  source__script__id: number | null;
  target__language__id: number | null;
  target__script__id: number | null;
  updated_at: Timestamp | null;
}

export interface LanguageExample {
  citation__id: Int8 | null;
  english_translation: string | null;
  id: Generated<Int8>;
  position: Generated<number>;
  provider: string | null;
  script__id: number | null;
  string__id: Int8 | null;
  text: string;
  updated_at: Timestamp | null;
}

export interface LanguageMinimalPair {
  difference: number;
  id: Generated<Int8>;
  language__id: number | null;
  source__id: Int8;
  target__id: Int8;
}

export interface LanguageMinimalPairList {
  id: Generated<number>;
  language__id: number;
  path: string;
}

export interface LanguageMinimalPairListItem {
  id: Int8;
  list__id: number;
  pair__id: number;
  position: number;
}

export interface LanguagePage {
  id: Generated<Int8>;
  language__id: number;
  page__id: Int8;
}

export interface LanguagePronunciation {
  accent__id: number | null;
  id: Generated<Int8>;
  ipa: string;
  is_canonical: boolean | null;
  pattern: string | null;
  pattern_simplified: string | null;
  position: Generated<number>;
  scheme__id: number | null;
  script__id: number | null;
  source: string | null;
  string__id: Int8;
  syllables__count: number | null;
  syllables__spans: Json | null;
  talk: string;
  updated_at: Timestamp | null;
  xsampa: string;
}

export interface LanguagePronunciationRecording {
  accent__id: number | null;
  file__id: Int8 | null;
  gender: string | null;
  id: Generated<Int8>;
  language__id: number;
  position: number | null;
  provider: string | null;
  system: string | null;
  text: string;
}

export interface LanguagePronunciationRecordingLink {
  id: Generated<Int8>;
  pronunciation__id: Int8;
  recording__id: Int8;
}

export interface LanguageRelated {
  id: Generated<Int8>;
  score: Generated<Numeric>;
  source__id: Int8;
  target__id: Int8;
}

export interface LanguageRhyme {
  component__id: number;
  id: Generated<Int8>;
  pronunciation__id: Int8;
  score: Generated<Numeric>;
}

export interface LanguageRhymeComponent {
  id: Generated<number>;
  text: string;
}

export interface LanguageSound {
  advanced_tongue_root: string | null;
  allophones__ipa: string[] | null;
  allophones__talk: string[] | null;
  allophones__xsampa: string[] | null;
  anterior: string | null;
  approximant: string | null;
  back: string | null;
  click: string | null;
  consonantal: string | null;
  constricted_glottis: string | null;
  continuant: string | null;
  coronal: string | null;
  delayed_release: string | null;
  distributed: string | null;
  dorsal: string | null;
  epilaryngeal_source: string | null;
  fortis: string | null;
  front: string | null;
  high: string | null;
  id: Generated<number>;
  ipa: string;
  labial: string | null;
  labiodental: string | null;
  language__id: number;
  lateral: string | null;
  lenis: string | null;
  long: string | null;
  low: string | null;
  lowered_larynx_implosive: string | null;
  marginal: string | null;
  nasal: string | null;
  periodic_glottal_source: string | null;
  phoible_id: string;
  raised_larynx_ejective: string | null;
  retracted_tongue_root: string | null;
  role: string | null;
  round: string | null;
  short: string | null;
  sonorant: string | null;
  spread_glottis: string | null;
  stress: string | null;
  stressed: string | null;
  strident: string | null;
  syllabic: string | null;
  talk: string | null;
  tap: string | null;
  tense: string | null;
  tone: string | null;
  trill: string | null;
  xsampa: string | null;
}

export interface LanguageString {
  affix: string | null;
  animacy: string | null;
  arity: number | null;
  aspect: string | null;
  beneficiary: string | null;
  case: string | null;
  category: string | null;
  class: string | null;
  concreteness: string | null;
  context__id: Int8 | null;
  continuity: string | null;
  countability: string | null;
  declension: number | null;
  definiteness: string | null;
  directionality: string | null;
  etymology: string | null;
  finiteness: string | null;
  focus: string | null;
  formality: string | null;
  frequency: Numeric | null;
  gender: string | null;
  group: string | null;
  has_predictable_meaning: boolean | null;
  head__id: string | null;
  id: Generated<Int8>;
  inclusivity: string | null;
  is_affix: boolean | null;
  is_alternative: boolean | null;
  is_auxiliary: boolean | null;
  is_base: boolean | null;
  is_borrowed: boolean | null;
  is_compound: boolean | null;
  is_derived: boolean | null;
  is_descendent: boolean | null;
  is_form: boolean | null;
  is_head: boolean | null;
  is_inflection: boolean | null;
  is_lead: boolean | null;
  is_modal: boolean | null;
  is_multi_word: boolean | null;
  is_norm: boolean | null;
  is_phrase: boolean | null;
  is_prefix: boolean | null;
  is_proper: boolean | null;
  is_root: boolean | null;
  is_suffix: boolean | null;
  is_syllable: boolean | null;
  is_term: boolean | null;
  is_terminating: boolean | null;
  is_translation: boolean | null;
  is_variant: boolean | null;
  is_word: boolean | null;
  language__id: number | null;
  likelihood: string | null;
  mood: string | null;
  mutation: boolean | null;
  origin__id: string | null;
  person: number | null;
  plurality: string | null;
  polarity: string | null;
  possessivity: string | null;
  rationality: string | null;
  regularity: string | null;
  relativity: string | null;
  respect: string | null;
  role: string | null;
  root__id: Int8 | null;
  specificity: string | null;
  structure: string | null;
  syllable__max: number | null;
  syllable__min: number | null;
  tense: string | null;
  text: string;
  transitivity: string | null;
  updated_at: Timestamp | null;
  voice: string | null;
}

export interface LanguageStringCollection {
  id: Generated<number>;
  slug: string;
  user__id: number;
}

export interface LanguageStringCollectionItem {
  collection__id: number;
  id: Generated<Int8>;
  slug: string;
  string__id: number;
}

export interface LanguageStringImage {
  id: Generated<Int8>;
  image__id: Int8;
  position: Generated<number>;
  string__id: Int8;
}

export interface LanguageStringList {
  id: Generated<number>;
  is_source: Generated<boolean>;
  language__id: number;
  path: string;
}

export interface LanguageStringListItem {
  id: Generated<number>;
  list__id: number | null;
  position: Generated<number>;
  string__id: Int8 | null;
}

export interface LanguageStringRelation {
  category: string;
  child__id: Int8 | null;
  id: Generated<Int8>;
  parent__id: Int8 | null;
}

export interface LanguageStringSearch {
  id: Generated<Int8>;
  is_phonetic: Generated<boolean | null>;
  language__id: number | null;
  length: Generated<number>;
  scheme__id: number | null;
  score: Generated<Numeric>;
  script__id: number | null;
  string__id: Int8 | null;
  symbol_frequencies: Json | null;
  text: string;
  text_reversed: string | null;
}

export interface LanguageStringWord {
  id: Generated<Int8>;
  position: Generated<number>;
  string__id: Int8;
  word__id: Int8;
}

export interface LanguageSymbol {
  id: Generated<Int8>;
  is_bound: boolean | null;
  language__id: number | null;
  numeric: string | null;
  role: string | null;
  script__id: number | null;
  talk: string | null;
}

export interface LanguageSymbolSet {
  id: Generated<Int8>;
  language__id: number | null;
}

export interface LanguageSymbolSetItem {
  id: Generated<Int8>;
  set__id: Int8 | null;
  symbol__id: Int8 | null;
}

export interface LanguageSymbolVideo {
  id: Generated<Int8>;
  position: Generated<number>;
  symbol__id: Int8;
  video__id: Int8;
}

export interface LanguageSynonym {
  id: Generated<Int8>;
  score: Generated<Numeric>;
  source__id: Int8;
  target__id: Int8;
}

export interface LanguageTranscription {
  has_diacritics: boolean | null;
  id: Generated<Int8>;
  is_canonical: boolean | null;
  is_lowercase: boolean | null;
  is_phonetic: boolean | null;
  is_uppercase: boolean | null;
  length: number;
  position: Generated<number>;
  scheme__id: number | null;
  script__id: number | null;
  source: string | null;
  string__id: Int8;
  text: string;
  updated_at: Timestamp | null;
}

export interface LanguageTranslation {
  id: Generated<Int8>;
  position: Generated<number>;
  source__id: Int8 | null;
  target__id: Int8 | null;
  updated_at: Timestamp | null;
}

export interface LanguageWord {
  id: Generated<Int8>;
  syllable__max: number | null;
  syllable__min: number | null;
  text: string;
}

export interface Link {
  id: Generated<Int8>;
  key: string | null;
  title: string | null;
  url: string;
}

export interface Metadata {
  description: string | null;
  id: Generated<Int8>;
  image__id: Int8 | null;
  keywords: string | null;
  object__id: string;
  object__type__id: Int8 | null;
  site__id: Int8 | null;
  title: string | null;
}

export interface MimeType {
  id: Generated<number>;
  key: string;
  value: string;
}

export interface MimeTypeExtensionAssociation {
  id: Generated<number>;
  mime__id: number | null;
  value: string;
}

export interface Page {
  audios__id: number | null;
  category: string;
  content: Generated<string>;
  created_at: Timestamp;
  description: string | null;
  documents__id: number | null;
  draft__id: Int8 | null;
  id: Generated<Int8>;
  image__id: Int8 | null;
  images__id: number | null;
  is_published: Generated<boolean>;
  keywords: string[] | null;
  live__id: Int8 | null;
  metadata: Json | null;
  path: string;
  published_at: Timestamp | null;
  strings__id: number | null;
  title: string;
  updated_at: Timestamp;
  videos__id: number | null;
}

export interface PageCollaborator {
  added_at: Timestamp;
  id: Generated<Int8>;
  is_public: Generated<boolean | null>;
  page__id: Int8;
  role: string;
  user__id: number;
}

export interface Redirect {
  from: string;
  id: Generated<Int8>;
  to: string;
}

export interface Script {
  category: string | null;
  id: Generated<number>;
  is_rtl: boolean | null;
  is_vertical: boolean | null;
  iso_15924: string | null;
  iso_15924_numeric: string | null;
  name: string;
  slug: string;
  tags: string[] | null;
  updated_at: Timestamp | null;
}

export interface ScriptCollaborator {
  added_at: Timestamp;
  id: Generated<Int8>;
  is_public: Generated<boolean | null>;
  role: string;
  script__id: Int8;
  user__id: number;
}

export interface ScriptLigature {
  id: Generated<Int8>;
  script__id: number | null;
  symbols: Json;
}

export interface ScriptPage {
  id: Generated<Int8>;
  page__id: Int8;
  script__id: number;
}

export interface ScriptSymbol {
  category: string;
  id: Generated<Int8>;
  is_combining: boolean | null;
  name__native__language__id: number | null;
  name__native__script__id: number | null;
  name__native__text: string | null;
  name__text: string | null;
  script__id: number | null;
  unicode__id: Int8 | null;
}

export interface Site {
  domain: string;
  id: Generated<Int8>;
}

export interface TableName {
  id: Generated<Int8>;
  name: string;
}

export interface Tag {
  id: Generated<Int8>;
  parent__id: Int8 | null;
  slug: string;
}

export interface TaskRateLimiter {
  expire: Int8 | null;
  key: string;
  points: Generated<number>;
}

export interface Text {
  id: Generated<number>;
  slug: string;
  title: string;
}

export interface TextCorpus {
  id: Generated<number>;
  slug: string;
}

export interface TextSection {
  category: string;
  id: Generated<Int8>;
  is_index: boolean | null;
  item_title: string | null;
  link__next__id: Int8 | null;
  link__previous__id: Int8 | null;
  parent__id: Int8 | null;
  path: string;
  position__column: Generated<number>;
  position__row: Generated<number>;
  status: string | null;
  title: string | null;
  version__id: number;
}

export interface TextSectionPart {
  id: Generated<Int8>;
  position: Generated<number>;
  section__id: Int8;
  span__id: Int8;
}

export interface TextSpan {
  content: string;
  id: Generated<Int8>;
  language__id: number | null;
  script__id: number | null;
}

export interface TextStringAppearance {
  id: Generated<Int8>;
  index: Generated<number>;
  position__end: Generated<number>;
  position__start: Generated<number>;
  section__id: Int8;
  string__id: Int8;
}

export interface TextStringAppearanceSummary {
  count: Generated<number>;
  id: Generated<Int8>;
  section__id: Int8;
  string__id: Int8;
}

export interface TextVersion {
  id: Generated<number>;
  text__id: number;
}

export interface UnicodeBlock {
  id: Generated<number>;
  plane: number | null;
  range__end: number;
  range__start: number;
  slug: string;
  title: string;
}

export interface UnicodeGlyph {
  base_variant__id: Int8 | null;
  bidirectional_category: string | null;
  block__id: number | null;
  category: string | null;
  combining_class: string | null;
  components: string | null;
  display: string | null;
  east_asian_width: string | null;
  extra: Generated<Json | null>;
  extra_line_count: number | null;
  has_relationships: Generated<boolean>;
  has_variants: boolean | null;
  hex: string;
  id: Generated<Int8>;
  ideographic: boolean | null;
  indic_syllabic_category: string | null;
  integer: number;
  is_mirrored: Generated<boolean>;
  line_count: number | null;
  plane: number | null;
  radical: number | null;
  slug: string;
  title: string | null;
  unicode_version: Numeric;
  unified_ideograph: boolean | null;
}

export interface UnicodeGlyphRelationship {
  category: string;
  id: Generated<Int8>;
  source__id: Int8 | null;
  target__id: Int8 | null;
}

export interface UnicodeGlyphScript {
  glyph__id: Int8 | null;
  id: Generated<Int8>;
  script__id: number | null;
}

export interface User {
  created_at: Timestamp;
  description: string | null;
  id: Generated<number>;
  name: string;
  slug: string;
  supabase_id: string;
}

export interface Video {
  id: Generated<Int8>;
  path: string;
}

export interface VideoCollection {
  id: Generated<number>;
  path: string | null;
}

export interface VideoCollectionItem {
  collection__id: number;
  id: Generated<Int8>;
  slug: string;
  video__id: Int8;
}

export interface VideoFile {
  base__id: Int8;
  format: string;
  height: number | null;
  id: Generated<Int8>;
  url: string;
  width: number | null;
}

export interface VideoTag {
  content__id: Int8;
  id: Generated<Int8>;
  tag__id: Int8;
}

export interface DB {
  audio: Audio;
  audio_collection: AudioCollection;
  audio_collection_item: AudioCollectionItem;
  audio_file: AudioFile;
  audio_tag: AudioTag;
  base: Base;
  citation: Citation;
  citation_association: CitationAssociation;
  citation_author: CitationAuthor;
  citation_author_association: CitationAuthorAssociation;
  content_license: ContentLicense;
  content_usage: ContentUsage;
  corpus_string_appearance_summary: CorpusStringAppearanceSummary;
  country: Country;
  document: Document;
  document_collection: DocumentCollection;
  document_collection_item: DocumentCollectionItem;
  document_tag: DocumentTag;
  file_extension: FileExtension;
  file_node: FileNode;
  file_reference: FileReference;
  font: Font;
  font_pairing: FontPairing;
  font_tag: FontTag;
  font_variant: FontVariant;
  font_variant_chunk: FontVariantChunk;
  image: Image;
  image_collection: ImageCollection;
  image_collection_item: ImageCollectionItem;
  image_file: ImageFile;
  image_tag: ImageTag;
  integer: Integer;
  integer_sequence: IntegerSequence;
  integer_sequence_association: IntegerSequenceAssociation;
  integer_string_system: IntegerStringSystem;
  integer_transcription_binding: IntegerTranscriptionBinding;
  job: Job;
  label: Label;
  language: Language;
  language_accent: LanguageAccent;
  language_anagram: LanguageAnagram;
  language_anagram_permutation: LanguageAnagramPermutation;
  language_anagram_permutation_association: LanguageAnagramPermutationAssociation;
  language_antonym: LanguageAntonym;
  language_collaborator: LanguageCollaborator;
  language_country: LanguageCountry;
  language_definition: LanguageDefinition;
  language_definition_embedding: LanguageDefinitionEmbedding;
  language_encoding_scheme: LanguageEncodingScheme;
  language_example: LanguageExample;
  language_minimal_pair: LanguageMinimalPair;
  language_minimal_pair_list: LanguageMinimalPairList;
  language_minimal_pair_list_item: LanguageMinimalPairListItem;
  language_page: LanguagePage;
  language_pronunciation: LanguagePronunciation;
  language_pronunciation_recording: LanguagePronunciationRecording;
  language_pronunciation_recording_link: LanguagePronunciationRecordingLink;
  language_related: LanguageRelated;
  language_rhyme: LanguageRhyme;
  language_rhyme_component: LanguageRhymeComponent;
  language_sound: LanguageSound;
  language_string: LanguageString;
  language_string_collection: LanguageStringCollection;
  language_string_collection_item: LanguageStringCollectionItem;
  language_string_image: LanguageStringImage;
  language_string_list: LanguageStringList;
  language_string_list_item: LanguageStringListItem;
  language_string_relation: LanguageStringRelation;
  language_string_search: LanguageStringSearch;
  language_string_word: LanguageStringWord;
  language_symbol: LanguageSymbol;
  language_symbol_set: LanguageSymbolSet;
  language_symbol_set_item: LanguageSymbolSetItem;
  language_symbol_video: LanguageSymbolVideo;
  language_synonym: LanguageSynonym;
  language_transcription: LanguageTranscription;
  language_translation: LanguageTranslation;
  language_word: LanguageWord;
  link: Link;
  metadata: Metadata;
  mime_type: MimeType;
  mime_type_extension_association: MimeTypeExtensionAssociation;
  page: Page;
  page_collaborator: PageCollaborator;
  redirect: Redirect;
  script: Script;
  script_collaborator: ScriptCollaborator;
  script_ligature: ScriptLigature;
  script_page: ScriptPage;
  script_symbol: ScriptSymbol;
  site: Site;
  table_name: TableName;
  tag: Tag;
  task_rate_limiter: TaskRateLimiter;
  text: Text;
  text_corpus: TextCorpus;
  text_section: TextSection;
  text_section_part: TextSectionPart;
  text_span: TextSpan;
  text_string_appearance: TextStringAppearance;
  text_string_appearance_summary: TextStringAppearanceSummary;
  text_version: TextVersion;
  unicode_block: UnicodeBlock;
  unicode_glyph: UnicodeGlyph;
  unicode_glyph_relationship: UnicodeGlyphRelationship;
  unicode_glyph_script: UnicodeGlyphScript;
  user: User;
  video: Video;
  video_collection: VideoCollection;
  video_collection_item: VideoCollectionItem;
  video_file: VideoFile;
  video_tag: VideoTag;
}
